### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by efirshik** [rm-hull/luma.oled#358]
**sbc:** banana pi m1
**os:** Armbian 22.11.1 Bullseye
**uname -a:** Linux bananapi 5.15.80-sunxi 22.11.1 SMP Wed Nov 30 11:13:48 UTC 2022 armv7l GNU/Linux
**this  dependencies installed:** python3 python3-pip python3-pil libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjp2-7 libtiff5

```
python3 monitor.py
Traceback (most recent call last):
  File "/home/efirshik/luma.examples/examples/monitor.py", line 18, in <module>
    font = ImageFont.truetype(font_path, 12)
  File "/usr/local/lib/python3.9/dist-packages/PIL/ImageFont.py", line 976, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.9/dist-packages/PIL/ImageFont.py", line 973, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.9/dist-packages/PIL/ImageFont.py", line 221, in __init__
    if core.HAVE_RAQM:
  File "/usr/local/lib/python3.9/dist-packages/PIL/ImageFont.py", line 58, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

**Comment by efirshik** [comment]
sorry, find solution:

`sudo rm -rf /usr/local/lib/python3.9/dist-packages/PIL`

and now all work!
