### ISSUE TITLE
Input/output error for luma.oled

### ISSUE THREAD

**Issue by lmcpith** [rm-hull/luma.oled#372]
#### Linux Kernel version

5.4.0-139-generic

kindly suggest a version of luma that can work with linux ubuntu. might be timing or handhake. using oled 128x32 

#### Expected behaviour

trying to use luma.oled library under linux ubuntu
oled is well detected and well mapped under i2c but and mapped as 0x3c, visible
hoping to use this library under linux ubuntu 18

#### Actual behaviour

```
    device = ssd1306(serial)
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/oled/device.py", line 171, in __init__
    self.clear()
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/core/mixin.py", line 46, in clear
    self.display(Image.new(self.mode, self.size))
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/oled/device.py", line 200, in display
    self.data(list(buf))
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/core/interface/serial.py", line 131, in data
    write(list(data[i:i + block_size]))
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/luma/core/interface/serial.py", line 140, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/home/letmein/miniconda3/lib/python3.9/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error

```

**Comment by thijstriemstra** [comment]
what device are you using? can you link the datasheet or seller link?

**Comment by lmcpith** [comment]
HIbranded from china probably, part number is cm009605v4it works with arduino, I was retesting with Linux ubuntu
    On Monday, April 3, 2023 at 05:11:15 p.m. EDT, Thijs Triemstra ***@***.***> wrote:  
 
 


what device are you using? can you link the datasheet or seller link?

**Comment by ve2opn** [comment]
Exactly same error on latest Fedora Linux x64 and 2.42" ssd1309 i2c 128x64 module from here : https://www.aliexpress.com/item/1005003091769556.html
I needed to short D2 as explained to get it visible at 0x3c.  
The same example (terminal.py) works fine with two other smaller i2c modules based sh1106 and ssd1306 chips.
However with this one, starts and fails after a second-two working.
Typically: ... i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error

FYI, the module as HW on same host works well with this driver: https://github.com/armlabs/ssd1306_linux

**Comment by ve2opn** [comment]
#### Actual behaviour

```
[root@fedora examples]# python terminal.py -d ssd1309 --i2c-port 0
Version: luma.oled 3.12.0 (luma.core 2.4.0)
Display: ssd1309
Interface: i2c
Dimensions: 128 x 64
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/msh1/TEST/luma.examples/examples/terminal.py", line 82, in <module>
    main()
  File "/home/msh1/TEST/luma.examples/examples/terminal.py", line 31, in main
    term.println("Uses any font to output text using a number of different print methods.")
  File "/usr/local/lib/python3.11/site-packages/luma/core/virtual.py", line 288, in println
    self.puts(text)
  File "/usr/local/lib/python3.11/site-packages/luma/core/virtual.py", line 304, in puts
    method(*args)
  File "/usr/local/lib/python3.11/site-packages/luma/core/virtual.py", line 339, in putch
    self.flush()
  File "/usr/local/lib/python3.11/site-packages/luma/core/virtual.py", line 402, in flush
    self._device.display(self._backing_image)
  File "/usr/local/lib/python3.11/site-packages/luma/oled/device/__init__.py", line 310, in display
    self.data(list(buf))
  File "/usr/local/lib/python3.11/site-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/usr/local/lib/python3.11/site-packages/luma/core/interface/serial.py", line 131, in data
    write(list(data[i:i + block_size]))
  File "/usr/local/lib/python3.11/site-packages/luma/core/interface/serial.py", line 140, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/usr/local/lib/python3.11/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error
[root@fedora examples]#
```

**Comment by thijstriemstra** [comment]
> I was retesting with Linux ubuntu
> latest Fedora Linux/x86_64 6.3.11-200.fc38.x86_64 Kernel

Anyone can test this on Raspberry Pi OS? I don't have such a device so won't be able to test..

**Comment by Lenni** [comment]
I have the same issue on an Raspberry Pi 3B. The `demo.py `works without problems, but `terminal.py `crashes shortly after displaying the first line on the display.

`(.venv) cms@pi:~/luma.examples/examples $ python terminal.py --i2c-port 11 --display ssd1309 --inverse --i2c-address 0x3c
Version: luma.oled 3.14.0 (luma.core 2.4.2)
Display: ssd1309
Interface: i2c
Dimensions: 128 x 64
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cms/luma.examples/examples/terminal.py", line 82, in <module>
    main()
  File "/home/cms/luma.examples/examples/terminal.py", line 30, in main
    term.println("------------------")
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/virtual.py", line 286, in println
    self.puts(text)
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/virtual.py", line 302, in puts
    method(*args)
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/virtual.py", line 337, in putch
    self.flush()
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/virtual.py", line 400, in flush
    self._device.display(self._backing_image)
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/oled/device/__init__.py", line 311, in display
    self.data(list(buf))
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/interface/serial.py", line 128, in data
    write(list(data[i:i + block_size]))
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/luma/core/interface/serial.py", line 137, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/home/cms/dispenser/.venv/lib/python3.11/site-packages/smbus2/smbus2.py", line 660, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error
`

**Comment by Schuchmann** [comment]
Hi,
same Problem over here: I am using this one:
https://midasdisplays.com/shop/oled/oled-graphic/mcot128064b1v-wm/
which is a ssd1309 chip connected via i2c on a RaspberryPi Compute Module 4 with raspian/bookworm.
Kernel is 6.12.27

```
$ python terminal.py --i2c-port 1 --display ssd1309 --inverse --i2c-address 0x3c
Version: luma.oled 3.10.0 (luma.core 2.4.0)
Display: ssd1309
Interface: i2c
Dimensions: 128 x 64
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/genipi/flashboxx/luma.examples/examples/terminal.py", line 82, in <module>
    main()
  File "/home/genipi/flashboxx/luma.examples/examples/terminal.py", line 30, in main
    term.println("------------------")
  File "/usr/lib/python3/dist-packages/luma/core/virtual.py", line 288, in println
    self.puts(text)
  File "/usr/lib/python3/dist-packages/luma/core/virtual.py", line 304, in puts
    method(*args)
  File "/usr/lib/python3/dist-packages/luma/core/virtual.py", line 339, in putch
    self.flush()
  File "/usr/lib/python3/dist-packages/luma/core/virtual.py", line 402, in flush
    self._device.display(self._backing_image)
  File "/usr/lib/python3/dist-packages/luma/oled/device/__init__.py", line 225, in display
    self.data(list(buf))
  File "/usr/lib/python3/dist-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 131, in data
    write(list(data[i:i + block_size]))
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 140, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/usr/lib/python3/dist-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error
```
 I have written a small test program:
```
#!/usr/bin/env python3

from luma.core.interface.serial import i2c
from luma.core.render import canvas
from luma.oled.device import ssd1309
from time import sleep

serial = i2c(port=1, address=0x3C)
device = ssd1309(serial, rotate=2)

alive_counter = 0
while True:
    with canvas(device) as draw:
        draw.rectangle(device.bounding_box, outline="white", fill="black")
        draw.text((0, 0), f"GeniPi {alive_counter}", fill="white")

    sleep(1)
    alive_counter += 1
```
this also crashes after 2-3 cycles:
```
$ ./oled.py
Traceback (most recent call last):
  File "/home/user/oled.py", line 13, in <module>
    with canvas(device) as draw:
  File "/usr/lib/python3/dist-packages/luma/core/render.py", line 43, in __exit__
    self.device.display(self.image)
  File "/usr/lib/python3/dist-packages/luma/oled/device/__init__.py", line 225, in display
    self.data(list(buf))
  File "/usr/lib/python3/dist-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 131, in data
    write(list(data[i:i + block_size]))
  File "/usr/lib/python3/dist-packages/luma/core/interface/serial.py", line 140, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/usr/lib/python3/dist-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error
```
Can anyone help?
