### ISSUE TITLE
Orange  Pi zero2 error Timer expired

### ISSUE THREAD

**Issue by tbop-R** [rm-hull/luma.oled#375]
Hi
I'm using an OrangePI Zero2

#### Linux Kernel version
Linux 4.9.170-sun50iw9 #5 SMP PREEMPT Thu Dec 9 11:16:31 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

#### Expected behaviour
After connecting SDA, SCk, GND and VCC, I run python example:

python3 clock.py --i2c-port 3
`

#### Actual behaviour
The error I get is the following:

`Traceback (most recent call last):
  File "clock.py", line 69, in <module>
    device = get_device()
  File "luma.examples/examples/demo_opts.py", line 59, in get_device
    device = cmdline.create_device(args)
  File "/usr/local/lib/python3.8/dist-packages/luma/core/cmdline.py", line 239, in create_device
    device = Device(serial_interface=interface(), **params)
  File "/usr/local/lib/python3.8/dist-packages/luma/oled/device/__init__.py", line 278, in __init__
    self.clear()
  File "/usr/local/lib/python3.8/dist-packages/luma/core/mixin.py", line 46, in clear
    self.display(Image.new(self.mode, self.size))
  File "/usr/local/lib/python3.8/dist-packages/luma/oled/device/__init__.py", line 310, in display
    self.data(list(buf))
  File "/usr/local/lib/python3.8/dist-packages/luma/core/device.py", line 55, in data
    self._serial_interface.data(data)
  File "/usr/local/lib/python3.8/dist-packages/luma/core/interface/serial.py", line 131, in data
    write(list(data[i:i + block_size]))
  File "/usr/local/lib/python3.8/dist-packages/luma/core/interface/serial.py", line 140, in _write_large_block
    self._bus.i2c_rdwr(self._i2c_msg_write(self._addr, [self._data_mode] + data))
  File "/usr/local/lib/python3.8/dist-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 62] Timer expired
`

**Comment by thijstriemstra** [comment]
no feedback, closing.
